function getAllInputs() {
    return {
        "inputs": [{
            "componentId": "tkApplicantInfo",
            "componentTitle": "投保人信息",
            "applicantInfo": [{
                "componentId": "tkApplicantName",
                "tkId": "applicantName",
                "tkLable": "姓名",
                "tkTip": "投保人姓名",
                "tkDesc": "请输入投保人姓名",
                "tkRequired": true,
                "tkDefaultValue": "",
                "tkType": "",
                "tkOptions": ""
            }, {
                "componentId": "tkApplicantIdType",
                "tkId": "applicantIdType",
                "tkLable": "证件类型",
                "tkTip": "投保人证件类型",
                "tkDesc": "请选择投保人证件类型",
                "tkRequired": true,
                "tkDefaultValue": "",
                "tkType": "",
                "tkOptions": ""
            }, {
                "componentId": "tkApplicantId",
                "tkId": "applicantId",
                "tkLable": "证件号码",
                "tkTip": "投保人证件号码",
                "tkDesc": "请输入投保人证件号码",
                "tkRequired": true,
                "tkDefaultValue": "",
                "tkType": "",
                "tkOptions": ""
            }, {
                "componentId": "tkApplicantGender",
                "tkId": "applicantGender",
                "tkLable": "性别",
                "tkTip": "投保人性别",
                "tkDesc": "请输入投保性别",
                "tkRequired": true,
                "tkDefaultValue": "",
                "tkType": "",
                "tkOptions": ""
            }, {
                "componentId": "tkApplicantBirth",
                "tkId": "applicantBirth",
                "tkLable": "出生日期",
                "tkTip": "投保人出生日期",
                "tkDesc": "请输入投保人出生日期",
                "tkRequired": true,
                "tkDefaultValue": "",
                "tkType": "",
                "tkOptions": ""
            }, {
                "componentId": "tkApplicantPhone",
                "tkId": "applicantPhone",
                "tkLable": "手机号",
                "tkTip": "投保人手机号",
                "tkDesc": "请输入投保人手机号",
                "tkRequired": true,
                "tkDefaultValue": "",
                "tkType": "",
                "tkOptions": ""
            }, {
                "componentId": "tkApplicantEmail",
                "tkId": "applicantEmail",
                "tkLable": "电子邮箱",
                "tkTip": "投保人电子邮箱",
                "tkDesc": "请输入投保人电子邮箱",
                "tkRequired": true,
                "tkDefaultValue": "",
                "tkType": "",
                "tkOptions": ""
            }, {
                "componentId": "tkApplicantArea",
                "tkId": "applicantArea",
                "tkLable": "投保地区",
                "tkTip": "投保人投保地区",
                "tkDesc": "请输入投保人投保地区",
                "tkRequired": true,
                "tkDefaultValue": "",
                "tkType": "",
                "tkOptions": ""
            }, {
                "componentId": "tkApplicantProfession",
                "tkId": "applicantProfession",
                "tkLable": "职业类别",
                "tkTip": "投保人职业类别",
                "tkDesc": "请输入投保人职业类别",
                "tkRequired": true,
                "tkDefaultValue": "",
                "tkType": "",
                "tkOptions": ""
            }, {
                "componentId": "tkApplicantAddress",
                "tkId": "applicantAddress",
                "tkLable": "通讯地址",
                "tkTip": "投保人通讯地址",
                "tkDesc": "请输入投保人通讯地址",
                "tkRequired": true,
                "tkDefaultValue": "",
                "tkType": "",
                "tkOptions": ""
            }, {
                "componentId": "tkApplicantHealth",
                "tkId": "applicantHealth",
                "tkLable": "健康告知",
                "tkTip": "健康告知",
                "tkDesc": "有无健康告知",
                "tkRequired": true,
                "tkDefaultValue": false,
                "tkType": "",
                "tkOptions": ""
            }]
        }, {
            "componentId": "tkInsuredInfo",
            "componentTitle": "被保险人信息",
            "insuredInfo": [{
                "componentId": "tkInsuredRelationship",
                "tkId": "insuredRelationship",
                "tkLable": "与投保人的关系",
                "tkTip": "被保险人与投保人的关系",
                "tkDesc": "被保险人与投保人的关系",
                "tkRequired": true,
                "tkDefaultValue": "",
                "tkType": "",
                "tkOptions": ""
            }, {
                "componentId": "tkInsuredName",
                "tkId": "insuredName",
                "tkLable": "姓名",
                "tkTip": "被保险人姓名",
                "tkDesc": "请输入被保险人姓名",
                "tkRequired": true,
                "tkDefaultValue": "",
                "tkType": "",
                "tkOptions": ""
            }, {
                "componentId": "tkInsuredIdType",
                "tkId": "insuredIdType",
                "tkLable": "证件类型",
                "tkTip": "被保险人证件类型",
                "tkDesc": "请输入被保险人证件类型",
                "tkRequired": true,
                "tkDefaultValue": "",
                "tkType": "",
                "tkOptions": ""
            }, {
                "componentId": "tkInsuredId",
                "tkId": "insuredId",
                "tkLable": "证件号码",
                "tkTip": "被保险人证件号码",
                "tkDesc": "请输入被保险人证件号码",
                "tkRequired": true,
                "tkDefaultValue": "",
                "tkType": "",
                "tkOptions": ""
            }, {
                "componentId": "tkInsuredGender",
                "tkId": "insuredGender",
                "tkLable": "性别",
                "tkTip": "被保险人性别",
                "tkDesc": "请输入被保险人性别",
                "tkRequired": true,
                "tkDefaultValue": "",
                "tkType": "",
                "tkOptions": ""
            }, {
                "componentId": "tkInsuredBirth",
                "tkId": "insuredBirth",
                "tkLable": "出生日期",
                "tkTip": "被保险人出生日期",
                "tkDesc": "请输入被保险人出生日期",
                "tkRequired": true,
                "tkDefaultValue": "",
                "tkType": "",
                "tkOptions": ""
            }, {
                "componentId": "tkInsuredPersonCount",
                "tkId": "insuredPersonCount",
                "tkLable": "被保险人数",
                "tkTip": "最多被保险人数",
                "tkDesc": "请输入被保险人数",
                "tkRequired": true,
                "tkDefaultValue": "",
                "tkType": "",
                "tkOptions": ""
            }]
        }, {
            "componentId": "tkBeneficiaryInfo",
            "componentTitle": "受益人信息",
            "beneficiaryInfo": [{
                "componentId": "tkBeneficiaryPerson",
                "tkId": "beneficiaryPerson",
                "tkLable": "受益人",
                "tkTip": "受益人是谁(本人还是其它)",
                "tkDesc": "请选择受益人",
                "tkRequired": true,
                "tkDefaultValue": "",
                "tkType": "",
                "tkOptions": {
                    "法定": "01",
                    "指定": "02"
                }
            }, {
                "componentId": "tkBeneficiaryRelationship",
                "tkId": "beneficiaryRelationship",
                "tkLable": "受益人",
                "tkTip": "与投保人关系",
                "tkDesc": "请选择受益人和投保人关系",
                "tkRequired": true,
                "tkDefaultValue": "",
                "tkType": "",
                "tkOptions": ""
            }, {
                "componentId": "tkBeneficiaryPercent",
                "tkId": "beneficiaryPercent",
                "tkLable": "受益比例",
                "tkTip": "受益比例",
                "tkDesc": "请输入受益比例",
                "tkRequired": true,
                "tkDefaultValue": "",
                "tkType": "",
                "tkOptions": ""
            }, {
                "componentId": "tkBeneficiaryName",
                "tkId": "beneficiaryName",
                "tkLable": "姓名",
                "tkTip": "受益人姓名",
                "tkDesc": "请输入受益人姓名",
                "tkRequired": true,
                "tkDefaultValue": "",
                "tkType": "",
                "tkOptions": ""
            }, {
                "componentId": "tkBeneficiaryIdType",
                "tkId": "beneficiaryIdType",
                "tkLable": "证件类型",
                "tkTip": "受益人证件类型",
                "tkDesc": "请选择受益人证件类型",
                "tkRequired": true,
                "tkDefaultValue": "",
                "tkType": "",
                "tkOptions": ""
            }, {
                "componentId": "tkBeneficiaryId",
                "tkId": "beneficiaryId",
                "tkLable": "证件号码",
                "tkTip": "受益人证件号码",
                "tkDesc": "请选择受益人证件号码",
                "tkRequired": true,
                "tkDefaultValue": "",
                "tkType": "",
                "tkOptions": ""
            }, {
                "componentId": "tkBeneficiaryPersonCount",
                "tkId": "beneficiaryPersonCount",
                "tkLable": "受益人数",
                "tkTip": "最多受益人数",
                "tkDesc": "请输入最多受益人数",
                "tkRequired": true,
                "tkDefaultValue": "",
                "tkType": "",
                "tkOptions": ""
            }]
        }, {
            "componentId": "tkOtherInfo",
            "componentTitle": "其它信息",
            "otherInfo": [{
                "componentId": "tkOtherPerson",
                "tkId": "otherPerson",
                "tkLable": "推荐人信息",
                "tkTip": "推荐人是谁",
                "tkDesc": "请选择推荐人",
                "tkRequired": true,
                "tkDefaultValue": "",
                "tkType": "",
                "tkOptions": ""
            }, {
                "componentId": "tkOtherInvoice",
                "tkId": "otherInvoice",
                "tkLable": "是否需要发票",
                "tkTip": "是否需要发票",
                "tkDesc": "请选择是否需要发票",
                "tkRequired": true,
                "tkDefaultValue": "",
                "tkType": "",
                "tkOptions": ""
            }, {
                "componentId": "tkOtherPolicy",
                "tkId": "otherPolicy",
                "tkLable": "保单传达",
                "tkTip": "保单传达",
                "tkDesc": "请选择保单传达",
                "tkRequired": true,
                "tkDefaultValue": "",
                "tkType": "",
                "tkOptions": ""
            }, {
                "componentId": "tkOtherIntegral",
                "tkId": "otherIntegral",
                "tkLable": "使用积分",
                "tkTip": "使用积分",
                "tkDesc": "请选择使用积分",
                "tkRequired": true,
                "tkDefaultValue": "",
                "tkType": "",
                "tkOptions": ""
            }, {
                "componentId": "tkOtherDiscount",
                "tkId": "otherDiscount",
                "tkLable": "使用优惠",
                "tkTip": "使用优惠",
                "tkDesc": "请选择使用优惠",
                "tkRequired": true,
                "tkDefaultValue": "",
                "tkType": "",
                "tkOptions": ""
            }]
        }]
    };
}
