var payArea={
	"hotCity": [{
		"id": "1",
		"firstChar": "BEI JING",
		"name": "北京",
		"value": "北京",
		"only": "p_002",
		"type": "province"
	}, {
		"id": "2",
		"firstChar": "GUANG DONG",
		"name": "广东",
		"value": "广东",
		"only": "p_006",
		"type": "province"
	}, {
		"id": "3",
		"firstChar": "SHAN DONG",
		"name": "山东",
		"value": "山东",
		"only": "p_024",
		"type": "province"
	}, {
		"id": "4",
		"firstChar": "JIANG SU",
		"name": "江苏",
		"value": "江苏",
		"only": "p_016",
		"type": "province"
	}, {
		"id": "5",
		"firstChar": "HU BEI",
		"name": "湖北",
		"value": "湖北",
		"only": "p_013",
		"type": "province"
	}, {
		"id": "6",
		"firstChar": "ZHE JIANG",
		"name": "浙江",
		"value": "浙江",
		"only": "p_033",
		"type": "province"
	}, {
		"id": "7",
		"firstChar": "FU JIAN",
		"name": "福建",
		"value": "福建",
		"only": "p_004",
		"type": "province"
	}, {
		"id": "8",
		"firstChar": "HEI LONG JIANG",
		"name": "黑龙江",
		"value": "黑龙江",
		"only": "p_012",
		"type": "province"
	}, {
		"id": "9",
		"firstChar": "SHANG HAI",
		"name": "上海",
		"value": "上海",
		"only": "p_027",
		"type": "province"
	}, {
		"id": "10",
		"firstChar": "AN HUI",
		"name": "安徽",
		"value": "安徽",
		"only": "p_001",
		"type": "province"
	}],
	"items": [{
		"id": "1",
		"firstChar": "AN HUI ",
		"name": "安徽",
		"value": "安徽",
		"only": "p_001",
		"type": "province",
		"codeId":""
	}, {
		"id": "2",
		"ebaNo": "1714",
		"name": "安庆",
		"value": "J50",
		"province": "安徽",
		"only": "c_001",
		"type": "city"
	}, {
		"id": "3",
		"ebaNo": "1712",
		"name": "蚌埠",
		"value": "J30",
		"province": "安徽",
		"only": "c_002",
		"type": "city"
	}, {
		"id": "4",
		"ebaNo": "1726",
		"name": "池州",
		"value": "JH0",
		"province": "安徽",
		"only": "c_004",
		"type": "city"
	}, {
		"id": "5",
		"ebaNo": "1718",
		"name": "滁州",
		"value": "J90",
		"province": "安徽",
		"only": "c_005",
		"type": "city"
	}, {
		"id": "6",
		"ebaNo": "1720",
		"name": "阜阳",
		"value": "JB0",
		"province": "安徽",
		"only": "c_006",
		"type": "city"
	}, {
		"id": "7",
		"ebaNo": "1701",
		"name": "合肥",
		"value": "J10",
		"province": "安徽",
		"only": "c_007",
		"type": "city"
	}, {
		"id": "8",
		"ebaNo": "1723",
		"name": "淮北",
		"value": "JE0",
		"province": "安徽",
		"only": "c_008",
		"type": "city"
	}, {
		"id": "9",
		"ebaNo": "1715",
		"name": "淮南",
		"value": "J60",
		"province": "安徽",
		"only": "c_009",
		"type": "city"
	}, {
		"id": "10",
		"ebaNo": "1724",
		"name": "黄山",
		"value": "JF0",
		"province": "安徽",
		"only": "c_010",
		"type": "city"
	}, {
		"id": "11",
		"ebaNo": "1716",
		"name": "六安",
		"value": "J70",
		"province": "安徽",
		"only": "c_011",
		"type": "city"
	}, {
		"id": "12",
		"ebaNo": "1711",
		"name": "马鞍山",
		"value": "J20",
		"province": "安徽",
		"only": "c_012",
		"type": "city"
	}, {
		"id": "13",
		"ebaNo": "1719",
		"name": "宿州",
		"value": "JA0",
		"province": "安徽",
		"only": "c_013",
		"type": "city"
	}, {
		"id": "14",
		"ebaNo": "1725",
		"name": "铜陵",
		"value": "JG0",
		"province": "安徽",
		"only": "c_014",
		"type": "city"
	}, {
		"id": "15",
		"ebaNo": "1713",
		"name": "芜湖",
		"value": "J40",
		"province": "安徽",
		"only": "c_015",
		"type": "city"
	}, {
		"id": "16",
		"ebaNo": "1717",
		"name": "宣城",
		"value": "J80",
		"province": "安徽",
		"only": "c_016",
		"type": "city"
	}, {
		"id": "17",
		"ebaNo": "1722",
		"name": "亳州",
		"value": "JD0",
		"province": "安徽",
		"only": "c_017",
		"type": "city"
	}, {
		"id": "18",
		"firstChar": "BEI JING ",
		"name": "北京",
		"value": "北京",
		"only": "p_002",
		"type": "province",
		"codeId":"1"
	}, {
		"id": "19",
		"ebaNo": "0101",
		"name": "北京",
		"value": "110",
		"province": "北京",
		"only": "c_018",
		"type": "city",
		"codeId":"10"
	}, {
		"id": "20",
		"ebaNo": "1801",
		"name": "大连",
		"value": "K10",
		"province": "辽宁",
		"only": "c_019",
		"type": "city"
	}, {
		"id": "21",
		"firstChar": "FU JIAN ",
		"name": "福建",
		"value": "福建",
		"only": "p_004",
		"type": "province",
		"codeId":"G"
	}, {
		"id": "22",
		"ebaNo": "1401",
		"name": "福州",
		"value": "G10",
		"province": "福建",
		"only": "c_020",
		"type": "city"
	}, {
		"id": "23",
		"ebaNo": "1418",
		"name": "龙岩",
		"value": "G90",
		"province": "福建",
		"only": "c_021",
		"type": "city"
	}, {
		"id": "24",
		"ebaNo": "1411",
		"name": "南平",
		"value": "G20",
		"province": "福建",
		"only": "c_022",
		"type": "city"
	}, {
		"id": "25",
		"ebaNo": "1414",
		"name": "宁德",
		"value": "G50",
		"province": "福建",
		"only": "c_023",
		"type": "city"
	}, {
		"id": "26",
		"ebaNo": "1416",
		"name": "莆田",
		"value": "G70",
		"province": "福建",
		"only": "c_024",
		"type": "city"
	}, {
		"id": "27",
		"ebaNo": "1412",
		"name": "泉州",
		"value": "G30",
		"province": "福建",
		"only": "c_025",
		"type": "city"
	}, {
		"id": "28",
		"ebaNo": "1417",
		"name": "三明",
		"value": "G80",
		"province": "福建",
		"only": "c_026",
		"type": "city"
	}, {
		"id": "29",
		"ebaNo": "2901",
		"name": "厦门",
		"value": "G60",
		"province": "福建",
		"only": "c_027",
		"type": "city"
	}, {
		"id": "30",
		"ebaNo": "1413",
		"name": "漳州",
		"value": "G40",
		"province": "福建",
		"only": "c_028",
		"type": "city"
	}, {
		"id": "31",
		"firstChar": "GAN SU ",
		"name": "甘肃",
		"value": "甘肃",
		"only": "p_005",
		"type": "province"
	}, {
		"id": "32",
		"ebaNo": "3215",
		"name": "白银",
		"value": "W60",
		"province": "甘肃",
		"only": "c_029",
		"type": "city"
	}, {
		"id": "33",
		"ebaNo": "3217",
		"name": "定西",
		"value": "W80",
		"province": "甘肃",
		"only": "c_030",
		"type": "city"
	}, {
		"id": "34",
		"ebaNo": "3218",
		"name": "金昌",
		"value": "WB0",
		"province": "甘肃",
		"only": "c_031",
		"type": "city"
	}, {
		"id": "35",
		"ebaNo": "3214",
		"name": "酒泉",
		"value": "W70",
		"province": "甘肃",
		"only": "c_032",
		"type": "city"
	}, {
		"id": "36",
		"ebaNo": "3201",
		"name": "兰州",
		"value": "W10",
		"province": "甘肃",
		"only": "c_033",
		"type": "city"
	}, {
		"id": "37",
		"ebaNo": "3219",
		"name": "陇南",
		"value": "WC0",
		"province": "甘肃",
		"only": "c_034",
		"type": "city"
	}, {
		"id": "38",
		"ebaNo": "3216",
		"name": "平凉",
		"value": "WA0",
		"province": "甘肃",
		"only": "c_035",
		"type": "city"
	}, {
		"id": "39",
		"ebaNo": "3212",
		"name": "天水",
		"value": "W30",
		"province": "甘肃",
		"only": "c_036",
		"type": "city"
	}, {
		"id": "40",
		"ebaNo": "3211",
		"name": "武威",
		"value": "W20",
		"province": "甘肃",
		"only": "c_037",
		"type": "city"
	}, {
		"id": "41",
		"ebaNo": "3213",
		"name": "张掖",
		"value": "W50",
		"province": "甘肃",
		"only": "c_038",
		"type": "city"
	}, {
		"id": "42",
		"firstChar": "GUANG DONG ",
		"name": "广东",
		"value": "广东",
		"only": "p_006",
		"type": "province",
		"codeId":"3"
	}, {
		"id": "43",
		"ebaNo": "0323",
		"name": "潮州",
		"value": "3E0",
		"province": "广东",
		"only": "c_039",
		"type": "city"
	}, {
		"id": "44",
		"ebaNo": "0312",
		"name": "东莞",
		"value": "330",
		"province": "广东",
		"only": "c_040",
		"type": "city"
	}, {
		"id": "45",
		"ebaNo": "0311",
		"name": "佛山",
		"value": "320",
		"province": "广东",
		"only": "c_041",
		"type": "city"
	}, {
		"id": "46",
		"ebaNo": "0301",
		"name": "广州",
		"value": "310",
		"province": "广东",
		"only": "c_042",
		"type": "city"
	}, {
		"id": "47",
		"ebaNo": "0326",
		"name": "河源",
		"value": "3H0",
		"province": "广东",
		"only": "c_043",
		"type": "city"
	}, {
		"id": "48",
		"ebaNo": "0320",
		"name": "惠州",
		"value": "3B0",
		"province": "广东",
		"only": "c_044",
		"type": "city"
	}, {
		"id": "49",
		"ebaNo": "0314",
		"name": "江门",
		"value": "350",
		"province": "广东",
		"only": "c_045",
		"type": "city"
	}, {
		"id": "50",
		"ebaNo": "0324",
		"name": "揭阳",
		"value": "3F0",
		"province": "广东",
		"only": "c_046",
		"type": "city"
	}, {
		"id": "51",
		"ebaNo": "0317",
		"name": "茂名",
		"value": "380",
		"province": "广东",
		"only": "c_047",
		"type": "city"
	}, {
		"id": "52",
		"ebaNo": "0322",
		"name": "梅州",
		"value": "3D0",
		"province": "广东",
		"only": "c_048",
		"type": "city"
	}, {
		"id": "53",
		"ebaNo": "0327",
		"name": "清远",
		"value": "3I0",
		"province": "广东",
		"only": "c_049",
		"type": "city"
	}, {
		"id": "54",
		"ebaNo": "0316",
		"name": "汕头",
		"value": "370",
		"province": "广东",
		"only": "c_050",
		"type": "city"
	}, {
		"id": "55",
		"ebaNo": "0325",
		"name": "汕尾",
		"value": "3G0",
		"province": "广东",
		"only": "c_051",
		"type": "city"
	}, {
		"id": "56",
		"ebaNo": "0321",
		"name": "韶关",
		"value": "3C0",
		"province": "广东",
		"only": "c_052",
		"type": "city"
	}, {
		"id": "57",
		"ebaNo": "0329",
		"name": "阳江",
		"value": "3K0",
		"province": "广东",
		"only": "c_053",
		"type": "city"
	}, {
		"id": "58",
		"ebaNo": "0328",
		"name": "云浮",
		"value": "3J0",
		"province": "广东",
		"only": "c_054",
		"type": "city"
	}, {
		"id": "59",
		"ebaNo": "0318",
		"name": "湛江",
		"value": "390",
		"province": "广东",
		"only": "c_055",
		"type": "city"
	}, {
		"id": "60",
		"ebaNo": "0319",
		"name": "肇庆",
		"value": "3A0",
		"province": "广东",
		"only": "c_056",
		"type": "city"
	}, {
		"id": "61",
		"ebaNo": "0313",
		"name": "中山",
		"value": "340",
		"province": "广东",
		"only": "c_057",
		"type": "city"
	}, {
		"id": "62",
		"ebaNo": "0315",
		"name": "珠海",
		"value": "360",
		"province": "广东",
		"only": "c_058",
		"type": "city"
	}, {
		"id": "63",
		"firstChar": "GUANG XI ",
		"name": "广西",
		"value": "广西",
		"only": "p_007",
		"type": "province"
	}, {
		"id": "64",
		"ebaNo": "2516",
		"name": "百色",
		"value": "U60",
		"province": "广西",
		"only": "c_059",
		"type": "city"
	}, {
		"id": "65",
		"ebaNo": "2517",
		"name": "北海",
		"value": "U90",
		"province": "广西",
		"only": "c_060",
		"type": "city"
	}, {
		"id": "66",
		"ebaNo": "2521",
		"name": "崇左",
		"value": "UE0",
		"province": "广西",
		"only": "c_061",
		"type": "city"
	}, {
		"id": "67",
		"ebaNo": "2520",
		"name": "防城港",
		"value": "UD0",
		"province": "广西",
		"only": "c_062",
		"type": "city"
	}, {
		"id": "68",
		"ebaNo": "2513",
		"name": "桂林",
		"value": "U40",
		"province": "广西",
		"only": "c_063",
		"type": "city"
	}, {
		"id": "69",
		"ebaNo": "2519",
		"name": "贵港",
		"value": "UC0",
		"province": "广西",
		"only": "c_064",
		"type": "city"
	}, {
		"id": "70",
		"ebaNo": "2515",
		"name": "河池",
		"value": "U70",
		"province": "广西",
		"only": "c_065",
		"type": "city"
	}, {
		"id": "71",
		"ebaNo": "0",
		"name": "贺州",
		"value": "UA0",
		"province": "广西",
		"only": "c_066",
		"type": "city"
	}, {
		"id": "72",
		"ebaNo": "0",
		"name": "来宾",
		"value": "UB0",
		"province": "广西",
		"only": "c_067",
		"type": "city"
	}, {
		"id": "73",
		"ebaNo": "2511",
		"name": "柳州",
		"value": "U20",
		"province": "广西",
		"only": "c_068",
		"type": "city"
	}, {
		"id": "74",
		"ebaNo": "2501",
		"name": "南宁",
		"value": "U10",
		"province": "广西",
		"only": "c_069",
		"type": "city"
	}, {
		"id": "75",
		"ebaNo": "2518",
		"name": "钦州",
		"value": "U80",
		"province": "广西",
		"only": "c_070",
		"type": "city"
	}, {
		"id": "76",
		"ebaNo": "2512",
		"name": "梧州",
		"value": "U30",
		"province": "广西",
		"only": "c_071",
		"type": "city"
	}, {
		"id": "77",
		"ebaNo": "2514",
		"name": "玉林",
		"value": "U50",
		"province": "广西",
		"only": "c_072",
		"type": "city"
	}, {
		"id": "78",
		"firstChar": "GUI ZHOU ",
		"name": "贵州",
		"value": "贵州",
		"only": "p_008",
		"type": "province"
	}, {
		"id": "79",
		"ebaNo": "3112",
		"name": "安顺",
		"value": "Y50",
		"province": "贵州",
		"only": "c_073",
		"type": "city"
	}, {
		"id": "80",
		"ebaNo": "3116",
		"name": "毕节",
		"value": "Y70",
		"province": "贵州",
		"only": "c_074",
		"type": "city"
	}, {
		"id": "81",
		"ebaNo": "3115",
		"name": "都匀",
		"value": "Y60",
		"province": "贵州",
		"only": "c_075",
		"type": "city"
	}, {
		"id": "82",
		"ebaNo": "3101",
		"name": "贵阳",
		"value": "Y10",
		"province": "贵州",
		"only": "c_076",
		"type": "city"
	}, {
		"id": "83",
		"ebaNo": "3113",
		"name": "六盘水",
		"value": "Y30",
		"province": "贵州",
		"only": "c_077",
		"type": "city"
	}, {
		"id": "84",
		"ebaNo": "3114",
		"name": "黔东南",
		"value": "Y40",
		"province": "贵州",
		"only": "c_078",
		"type": "city"
	}, {
		"id": "85",
		"ebaNo": "3117",
		"name": "黔西南",
		"value": "Y90",
		"province": "贵州",
		"only": "c_079",
		"type": "city"
	}, {
		"id": "86",
		"ebaNo": "3118",
		"name": "铜仁",
		"value": "Y80",
		"province": "贵州",
		"only": "c_080",
		"type": "city"
	}, {
		"id": "87",
		"ebaNo": "3111",
		"name": "遵义",
		"value": "Y20",
		"province": "贵州",
		"only": "c_081",
		"type": "city"
	}, {
		"id": "88",
		"firstChar": "HAI NAN ",
		"name": "海南",
		"value": "海南",
		"only": "p_009",
		"type": "province",
		"codeId":"8"
	}, {
		"id": "89",
		"ebaNo": "3301",
		"name": "海口",
		"value": "810",
		"province": "海南",
		"only": "c_082",
		"type": "city"
	}, {
		"id": "90",
		"firstChar": "HE BEI ",
		"name": "河北",
		"value": "河北",
		"only": "p_010",
		"type": "province"
	}, {
		"id": "91",
		"ebaNo": "2115",
		"name": "保定",
		"value": "N60",
		"province": "河北",
		"only": "c_086",
		"type": "city"
	}, {
		"id": "92",
		"ebaNo": "2116",
		"name": "沧州",
		"value": "N80",
		"province": "河北",
		"only": "c_087",
		"type": "city"
	}, {
		"id": "93",
		"ebaNo": "2119",
		"name": "承德",
		"value": "NA0",
		"province": "河北",
		"only": "c_088",
		"type": "city"
	}, {
		"id": "94",
		"ebaNo": "2114",
		"name": "邯郸",
		"value": "N50",
		"province": "河北",
		"only": "c_089",
		"type": "city"
	}, {
		"id": "95",
		"ebaNo": "2118",
		"name": "衡水",
		"value": "N90",
		"province": "河北",
		"only": "c_090",
		"type": "city"
	}, {
		"id": "96",
		"ebaNo": "2111",
		"name": "廊坊",
		"value": "N20",
		"province": "河北",
		"only": "c_091",
		"type": "city"
	}, {
		"id": "97",
		"ebaNo": "2112",
		"name": "秦皇岛",
		"value": "N30",
		"province": "河北",
		"only": "c_092",
		"type": "city"
	}, {
		"id": "98",
		"ebaNo": "2101",
		"name": "石家庄",
		"value": "N10",
		"province": "河北",
		"only": "c_093",
		"type": "city"
	}, {
		"id": "99",
		"ebaNo": "2113",
		"name": "唐山",
		"value": "N40",
		"province": "河北",
		"only": "c_094",
		"type": "city"
	}, {
		"id": "100",
		"ebaNo": "2117",
		"name": "邢台",
		"value": "N70",
		"province": "河北",
		"only": "c_095",
		"type": "city"
	}, {
		"id": "101",
		"ebaNo": "2120",
		"name": "张家口",
		"value": "NB0",
		"province": "河北",
		"only": "c_096",
		"type": "city"
	}, {
		"id": "102",
		"firstChar": "HE NAN ",
		"name": "河南",
		"value": "河南",
		"only": "p_011",
		"type": "province",
		"codeId":"D"
	}, {
		"id": "103",
		"ebaNo": "0813",
		"name": "安阳",
		"value": "D30",
		"province": "河南",
		"only": "c_097",
		"type": "city"
	}, {
		"id": "104",
		"ebaNo": "0823",
		"name": "鹤壁",
		"value": "DF0",
		"province": "河南",
		"only": "c_098",
		"type": "city"
	}, {
		"id": "105",
		"ebaNo": "0",
		"name": "济源",
		"value": "DI0",
		"province": "河南",
		"only": "c_099",
		"type": "city"
	}, {
		"id": "106",
		"ebaNo": "0818",
		"name": "焦作",
		"value": "D80",
		"province": "河南",
		"only": "c_100",
		"type": "city"
	}, {
		"id": "107",
		"ebaNo": "0820",
		"name": "开封",
		"value": "DA0",
		"province": "河南",
		"only": "c_101",
		"type": "city"
	}, {
		"id": "108",
		"ebaNo": "0816",
		"name": "洛阳",
		"value": "D50",
		"province": "河南",
		"only": "c_102",
		"type": "city"
	}, {
		"id": "109",
		"ebaNo": "0815",
		"name": "南阳",
		"value": "D40",
		"province": "河南",
		"only": "c_103",
		"type": "city"
	}, {
		"id": "110",
		"ebaNo": "0814",
		"name": "平顶山",
		"value": "D70",
		"province": "河南",
		"only": "c_104",
		"type": "city"
	}, {
		"id": "111",
		"ebaNo": "0822",
		"name": "三门峡",
		"value": "DD0",
		"province": "河南",
		"only": "c_105",
		"type": "city"
	}, {
		"id": "112",
		"ebaNo": "0819",
		"name": "商丘",
		"value": "DB0",
		"province": "河南",
		"only": "c_106",
		"type": "city"
	}, {
		"id": "113",
		"ebaNo": "0812",
		"name": "新乡",
		"value": "D60",
		"province": "河南",
		"only": "c_107",
		"type": "city"
	}, {
		"id": "114",
		"ebaNo": "0824",
		"name": "信阳",
		"value": "DG0",
		"province": "河南",
		"only": "c_108",
		"type": "city"
	}, {
		"id": "115",
		"ebaNo": "0817",
		"name": "许昌",
		"value": "D90",
		"province": "河南",
		"only": "c_109",
		"type": "city"
	}, {
		"id": "116",
		"ebaNo": "0801",
		"name": "郑州",
		"value": "D10",
		"province": "河南",
		"only": "c_110",
		"type": "city"
	}, {
		"id": "117",
		"ebaNo": "0821",
		"name": "周口",
		"value": "DC0",
		"province": "河南",
		"only": "c_111",
		"type": "city"
	}, {
		"id": "118",
		"ebaNo": "0825",
		"name": "驻马店",
		"value": "DE0",
		"province": "河南",
		"only": "c_112",
		"type": "city"
	}, {
		"id": "119",
		"ebaNo": "0826",
		"name": "漯河",
		"value": "DH0",
		"province": "河南",
		"only": "c_113",
		"type": "city"
	}, {
		"id": "120",
		"ebaNo": "0811",
		"name": "濮阳",
		"value": "D20",
		"province": "河南",
		"only": "c_114",
		"type": "city"
	}, {
		"id": "121",
		"firstChar": "HEI LONG JIANG ",
		"name": "黑龙江",
		"value": "黑龙江",
		"only": "p_012",
		"type": "province"
	}, {
		"id": "122",
		"ebaNo": "2213",
		"name": "大庆",
		"value": "O40",
		"province": "黑龙江",
		"only": "c_115",
		"type": "city"
	}, {
		"id": "123",
		"ebaNo": "2216",
		"name": "大兴安岭",
		"value": "O80",
		"province": "黑龙江",
		"only": "c_116",
		"type": "city"
	}, {
		"id": "124",
		"ebaNo": "2201",
		"name": "哈尔滨",
		"value": "O10",
		"province": "黑龙江",
		"only": "c_117",
		"type": "city"
	}, {
		"id": "125",
		"ebaNo": "2221",
		"name": "鹤岗",
		"value": "OA0",
		"province": "黑龙江",
		"only": "c_118",
		"type": "city"
	}, {
		"id": "126",
		"ebaNo": "2218",
		"name": "黑河",
		"value": "O90",
		"province": "黑龙江",
		"only": "c_119",
		"type": "city"
	}, {
		"id": "127",
		"ebaNo": "2220",
		"name": "鸡西",
		"value": "OB0",
		"province": "黑龙江",
		"only": "c_120",
		"type": "city"
	}, {
		"id": "128",
		"ebaNo": "2217",
		"name": "佳木斯",
		"value": "O70",
		"province": "黑龙江",
		"only": "c_121",
		"type": "city"
	}, {
		"id": "129",
		"ebaNo": "2214",
		"name": "牡丹江",
		"value": "O60",
		"province": "黑龙江",
		"only": "c_122",
		"type": "city"
	}, {
		"id": "130",
		"ebaNo": "2211",
		"name": "齐齐哈尔",
		"value": "O20",
		"province": "黑龙江",
		"only": "c_124",
		"type": "city"
	}, {
		"id": "131",
		"ebaNo": "2222",
		"name": "双鸭山",
		"value": "OD0",
		"province": "黑龙江",
		"only": "c_125",
		"type": "city"
	}, {
		"id": "132",
		"ebaNo": "2212",
		"name": "绥化",
		"value": "O30",
		"province": "黑龙江",
		"only": "c_126",
		"type": "city"
	}, {
		"id": "133",
		"ebaNo": "2215",
		"name": "伊春",
		"value": "O50",
		"province": "黑龙江",
		"only": "c_127",
		"type": "city"
	}, {
		"id": "134",
		"firstChar": "HU BEI ",
		"name": "湖北",
		"value": "湖北",
		"only": "p_013",
		"type": "province",
		"codeId":"2"
	}, {
		"id": "135",
		"ebaNo": "0221",
		"name": "鄂州",
		"value": "2C0",
		"province": "湖北",
		"only": "c_128",
		"type": "city"
	}, {
		"id": "136",
		"ebaNo": "0220",
		"name": "恩施",
		"value": "2D0",
		"province": "湖北",
		"only": "c_129",
		"type": "city"
	}, {
		"id": "137",
		"ebaNo": "0217",
		"name": "黄冈",
		"value": "2A0",
		"province": "湖北",
		"only": "c_130",
		"type": "city"
	}, {
		"id": "138",
		"ebaNo": "0214",
		"name": "黄石",
		"value": "260",
		"province": "湖北",
		"only": "c_131",
		"type": "city"
	}, {
		"id": "139",
		"ebaNo": "0216",
		"name": "荆门",
		"value": "270",
		"province": "湖北",
		"only": "c_132",
		"type": "city"
	}, {
		"id": "140",
		"ebaNo": "0215",
		"name": "荆州",
		"value": "240",
		"province": "湖北",
		"only": "c_133",
		"type": "city"
	}, {
		"id": "141",
		"ebaNo": "0223",
		"name": "潜江",
		"value": "2E0",
		"province": "湖北",
		"only": "c_134",
		"type": "city"
	}, {
		"id": "142",
		"ebaNo": "0213",
		"name": "十堰",
		"value": "250",
		"province": "湖北",
		"only": "c_135",
		"type": "city"
	}, {
		"id": "143",
		"ebaNo": "0222",
		"name": "随州",
		"value": "2B0",
		"province": "湖北",
		"only": "c_136",
		"type": "city"
	}, {
		"id": "144",
		"ebaNo": "0225",
		"name": "天门",
		"value": "2G0",
		"province": "湖北",
		"only": "c_137",
		"type": "city"
	}, {
		"id": "145",
		"ebaNo": "0201",
		"name": "武汉",
		"value": "210",
		"province": "湖北",
		"only": "c_138",
		"type": "city"
	}, {
		"id": "146",
		"ebaNo": "0224",
		"name": "仙桃",
		"value": "2F0",
		"province": "湖北",
		"only": "c_139",
		"type": "city"
	}, {
		"id": "147",
		"ebaNo": "0219",
		"name": "咸宁",
		"value": "290",
		"province": "湖北",
		"only": "c_140",
		"type": "city"
	}, {
		"id": "148",
		"ebaNo": "0212",
		"name": "襄樊",
		"value": "230",
		"province": "湖北",
		"only": "c_141",
		"type": "city"
	}, {
		"id": "149",
		"ebaNo": "0218",
		"name": "孝感",
		"value": "280",
		"province": "湖北",
		"only": "c_142",
		"type": "city"
	}, {
		"id": "150",
		"ebaNo": "0211",
		"name": "宜昌",
		"value": "220",
		"province": "湖北",
		"only": "c_143",
		"type": "city"
	}, {
		"id": "151",
		"firstChar": "HU NAN ",
		"name": "湖南",
		"value": "湖南",
		"only": "p_014",
		"type": "province"
	}, {
		"id": "152",
		"ebaNo": "1515",
		"name": "常德",
		"value": "H60",
		"province": "湖南",
		"only": "c_144",
		"type": "city"
	}, {
		"id": "153",
		"ebaNo": "1501",
		"name": "长沙",
		"value": "H10",
		"province": "湖南",
		"only": "c_145",
		"type": "city"
	}, {
		"id": "154",
		"ebaNo": "1516",
		"name": "郴州",
		"value": "H70",
		"province": "湖南",
		"only": "c_146",
		"type": "city"
	}, {
		"id": "155",
		"ebaNo": "1512",
		"name": "衡阳",
		"value": "H30",
		"province": "湖南",
		"only": "c_147",
		"type": "city"
	}, {
		"id": "156",
		"ebaNo": "1523",
		"name": "怀化",
		"value": "HB0",
		"province": "湖南",
		"only": "c_148",
		"type": "city"
	}, {
		"id": "157",
		"ebaNo": "1521",
		"name": "吉首",
		"value": "HD0",
		"province": "湖南",
		"only": "c_149",
		"type": "city"
	}, {
		"id": "158",
		"ebaNo": "1517",
		"name": "娄底",
		"value": "HA0",
		"province": "湖南",
		"only": "c_150",
		"type": "city"
	}, {
		"id": "159",
		"ebaNo": "1519",
		"name": "邵阳",
		"value": "H80",
		"province": "湖南",
		"only": "c_151",
		"type": "city"
	}, {
		"id": "160",
		"ebaNo": "1511",
		"name": "湘潭",
		"value": "H20",
		"province": "湖南",
		"only": "c_152",
		"type": "city"
	}, {
		"id": "161",
		"ebaNo": "1518",
		"name": "益阳",
		"value": "H90",
		"province": "湖南",
		"only": "c_153",
		"type": "city"
	}, {
		"id": "162",
		"ebaNo": "1520",
		"name": "永州",
		"value": "HE0",
		"province": "湖南",
		"only": "c_154",
		"type": "city"
	}, {
		"id": "163",
		"ebaNo": "1514",
		"name": "岳阳",
		"value": "H50",
		"province": "湖南",
		"only": "c_155",
		"type": "city"
	}, {
		"id": "164",
		"ebaNo": "1522",
		"name": "张家界",
		"value": "HC0",
		"province": "湖南",
		"only": "c_156",
		"type": "city"
	}, {
		"id": "165",
		"ebaNo": "1513",
		"name": "株洲",
		"value": "H40",
		"province": "湖南",
		"only": "c_157",
		"type": "city"
	}, {
		"id": "166",
		"firstChar": "JI LIN ",
		"name": "吉林",
		"value": "吉林",
		"only": "p_015",
		"type": "province"
	}, {
		"id": "167",
		"ebaNo": "2615",
		"name": "白城",
		"value": "Q60",
		"province": "吉林",
		"only": "c_158",
		"type": "city"
	}, {
		"id": "168",
		"ebaNo": "2618",
		"name": "白山",
		"value": "Q90",
		"province": "吉林",
		"only": "c_159",
		"type": "city"
	}, {
		"id": "169",
		"ebaNo": "2601",
		"name": "长春",
		"value": "Q10",
		"province": "吉林",
		"only": "c_160",
		"type": "city"
	}, {
		"id": "170",
		"ebaNo": "2611",
		"name": "吉林",
		"value": "Q20",
		"province": "吉林",
		"only": "c_161",
		"type": "city"
	}, {
		"id": "171",
		"ebaNo": "2617",
		"name": "辽源",
		"value": "Q80",
		"province": "吉林",
		"only": "c_162",
		"type": "city"
	}, {
		"id": "172",
		"ebaNo": "2616",
		"name": "四平",
		"value": "Q70",
		"province": "吉林",
		"only": "c_163",
		"type": "city"
	}, {
		"id": "173",
		"ebaNo": "2614",
		"name": "松原",
		"value": "Q50",
		"province": "吉林",
		"only": "c_164",
		"type": "city"
	}, {
		"id": "174",
		"ebaNo": "2612",
		"name": "通化",
		"value": "Q30",
		"province": "吉林",
		"only": "c_165",
		"type": "city"
	}, {
		"id": "175",
		"ebaNo": "2613",
		"name": "延吉",
		"value": "Q40",
		"province": "吉林",
		"only": "c_166",
		"type": "city"
	}, {
		"id": "176",
		"firstChar": "JIANG SU ",
		"name": "江苏",
		"value": "江苏",
		"only": "p_016",
		"type": "province",
		"codeId":"A"
	}, {
		"id": "177",
		"ebaNo": "0713",
		"name": "常州",
		"value": "A20",
		"province": "江苏",
		"only": "c_167",
		"type": "city"
	}, {
		"id": "178",
		"ebaNo": "0722",
		"name": "淮安",
		"value": "AD0",
		"province": "江苏",
		"only": "c_168",
		"type": "city"
	}, {
		"id": "179",
		"ebaNo": "0718",
		"name": "连云港",
		"value": "A90",
		"province": "江苏",
		"only": "c_169",
		"type": "city"
	}, {
		"id": "180",
		"ebaNo": "0701",
		"name": "南京",
		"value": "A10",
		"province": "江苏",
		"only": "c_170",
		"type": "city"
	}, {
		"id": "181",
		"ebaNo": "0716",
		"name": "南通",
		"value": "A70",
		"province": "江苏",
		"only": "c_171",
		"type": "city"
	}, {
		"id": "182",
		"ebaNo": "0711",
		"name": "苏州",
		"value": "A30",
		"province": "江苏",
		"only": "c_172",
		"type": "city"
	}, {
		"id": "183",
		"ebaNo": "0721",
		"name": "宿迁",
		"value": "AC0",
		"province": "江苏",
		"only": "c_173",
		"type": "city"
	}, {
		"id": "184",
		"ebaNo": "0719",
		"name": "泰州",
		"value": "AA0",
		"province": "江苏",
		"only": "c_174",
		"type": "city"
	}, {
		"id": "185",
		"ebaNo": "0712",
		"name": "无锡",
		"value": "A60",
		"province": "江苏",
		"only": "c_175",
		"type": "city"
	}, {
		"id": "186",
		"ebaNo": "0714",
		"name": "徐州",
		"value": "A50",
		"province": "江苏",
		"only": "c_176",
		"type": "city"
	}, {
		"id": "187",
		"ebaNo": "0720",
		"name": "盐城",
		"value": "AB0",
		"province": "江苏",
		"only": "c_177",
		"type": "city"
	}, {
		"id": "188",
		"ebaNo": "0715",
		"name": "扬州",
		"value": "A40",
		"province": "江苏",
		"only": "c_178",
		"type": "city"
	}, {
		"id": "189",
		"ebaNo": "0717",
		"name": "镇江",
		"value": "A80",
		"province": "江苏",
		"only": "c_179",
		"type": "city"
	}, {
		"id": "190",
		"firstChar": "JIANG XI ",
		"name": "江西",
		"value": "江西",
		"only": "p_017",
		"type": "province"
	}, {
		"id": "191",
		"ebaNo": "2716",
		"name": "抚州",
		"value": "T70",
		"province": "江西",
		"only": "c_180",
		"type": "city"
	}, {
		"id": "192",
		"ebaNo": "2711",
		"name": "赣州",
		"value": "T30",
		"province": "江西",
		"only": "c_181",
		"type": "city"
	}, {
		"id": "193",
		"ebaNo": "2715",
		"name": "吉安",
		"value": "T60",
		"province": "江西",
		"only": "c_182",
		"type": "city"
	}, {
		"id": "194",
		"ebaNo": "2718",
		"name": "景德镇",
		"value": "T90",
		"province": "江西",
		"only": "c_183",
		"type": "city"
	}, {
		"id": "195",
		"ebaNo": "2713",
		"name": "九江",
		"value": "T20",
		"province": "江西",
		"only": "c_184",
		"type": "city"
	}, {
		"id": "196",
		"ebaNo": "2701",
		"name": "南昌",
		"value": "T10",
		"province": "江西",
		"only": "c_185",
		"type": "city"
	}, {
		"id": "197",
		"ebaNo": "2720",
		"name": "萍乡",
		"value": "TB0",
		"province": "江西",
		"only": "c_186",
		"type": "city"
	}, {
		"id": "198",
		"ebaNo": "2714",
		"name": "上饶",
		"value": "T40",
		"province": "江西",
		"only": "c_187",
		"type": "city"
	}, {
		"id": "199",
		"ebaNo": "2717",
		"name": "新余",
		"value": "T80",
		"province": "江西",
		"only": "c_188",
		"type": "city"
	}, {
		"id": "200",
		"ebaNo": "2712",
		"name": "宜春",
		"value": "T50",
		"province": "江西",
		"only": "c_189",
		"type": "city"
	}, {
		"id": "201",
		"ebaNo": "2719",
		"name": "鹰谭",
		"value": "TA0",
		"province": "江西",
		"only": "c_190",
		"type": "city"
	}, {
		"id": "202",
		"firstChar": "LIAO NING ",
		"name": "辽宁",
		"value": "辽宁",
		"only": "p_018",
		"type": "province",
		"codeId":"6"
	}, {
		"id": "203",
		"ebaNo": "0611",
		"name": "鞍山",
		"value": "650",
		"province": "辽宁",
		"only": "c_191",
		"type": "city"
	}, {
		"id": "204",
		"ebaNo": "0613",
		"name": "本溪",
		"value": "630",
		"province": "辽宁",
		"only": "c_192",
		"type": "city"
	}, {
		"id": "205",
		"ebaNo": "0622",
		"name": "朝阳",
		"value": "6C0",
		"province": "辽宁",
		"only": "c_193",
		"type": "city"
	}, {
		"id": "206",
		"ebaNo": "0619",
		"name": "丹东",
		"value": "660",
		"province": "辽宁",
		"only": "c_194",
		"type": "city"
	}, {
		"id": "207",
		"ebaNo": "0612",
		"name": "抚顺",
		"value": "640",
		"province": "辽宁",
		"only": "c_195",
		"type": "city"
	}, {
		"id": "208",
		"ebaNo": "0621",
		"name": "阜新",
		"value": "6D0",
		"province": "辽宁",
		"only": "c_196",
		"type": "city"
	}, {
		"id": "209",
		"ebaNo": "0617",
		"name": "葫芦岛",
		"value": "690",
		"province": "辽宁",
		"only": "c_197",
		"type": "city"
	}, {
		"id": "210",
		"ebaNo": "0615",
		"name": "锦州",
		"value": "670",
		"province": "辽宁",
		"only": "c_198",
		"type": "city"
	}, {
		"id": "211",
		"ebaNo": "0616",
		"name": "辽阳",
		"value": "680",
		"province": "辽宁",
		"only": "c_199",
		"type": "city"
	}, {
		"id": "212",
		"ebaNo": "0618",
		"name": "盘锦",
		"value": "6A0",
		"province": "辽宁",
		"only": "c_200",
		"type": "city"
	}, {
		"id": "213",
		"ebaNo": "0601",
		"name": "沈阳",
		"value": "610",
		"province": "辽宁",
		"only": "c_201",
		"type": "city"
	}, {
		"id": "214",
		"ebaNo": "0620",
		"name": "铁岭",
		"value": "6B0",
		"province": "辽宁",
		"only": "c_202",
		"type": "city"
	}, {
		"id": "215",
		"ebaNo": "0614",
		"name": "营口",
		"value": "620",
		"province": "辽宁",
		"only": "c_203",
		"type": "city"
	}, {
		"id": "216",
		"firstChar": "NEI MENG GU ",
		"name": "内蒙古",
		"value": "内蒙古",
		"only": "p_019",
		"type": "province"
	}, {
		"id": "217",
		"ebaNo": "3021",
		"name": "阿拉善盟",
		"value": "VC0",
		"province": "内蒙古",
		"only": "c_204",
		"type": "city"
	}, {
		"id": "218",
		"ebaNo": "3014",
		"name": "巴彦淖尔",
		"value": "V50",
		"province": "内蒙古",
		"only": "c_205",
		"type": "city"
	}, {
		"id": "219",
		"ebaNo": "3011",
		"name": "包头",
		"value": "V20",
		"province": "内蒙古",
		"only": "c_206",
		"type": "city"
	}, {
		"id": "220",
		"ebaNo": "3013",
		"name": "赤峰",
		"value": "V40",
		"province": "内蒙古",
		"only": "c_207",
		"type": "city"
	}, {
		"id": "221",
		"ebaNo": "3012",
		"name": "鄂尔多斯",
		"value": "V30",
		"province": "内蒙古",
		"only": "c_208",
		"type": "city"
	}, {
		"id": "222",
		"ebaNo": "3001",
		"name": "呼和浩特",
		"value": "V10",
		"province": "内蒙古",
		"only": "c_209",
		"type": "city"
	}, {
		"id": "223",
		"ebaNo": "3015",
		"name": "呼伦贝尔",
		"value": "V70",
		"province": "内蒙古",
		"only": "c_210",
		"type": "city"
	}, {
		"id": "224",
		"ebaNo": "3016",
		"name": "通辽",
		"value": "V60",
		"province": "内蒙古",
		"only": "c_211",
		"type": "city"
	}, {
		"id": "225",
		"ebaNo": "3017",
		"name": "乌海",
		"value": "VA0",
		"province": "内蒙古",
		"only": "c_212",
		"type": "city"
	}, {
		"id": "226",
		"ebaNo": "3018",
		"name": "乌兰察布",
		"value": "V80",
		"province": "内蒙古",
		"only": "c_213",
		"type": "city"
	}, {
		"id": "227",
		"ebaNo": "3019",
		"name": "锡林郭勒",
		"value": "V90",
		"province": "内蒙古",
		"only": "c_214",
		"type": "city"
	}, {
		"id": "228",
		"ebaNo": "3020",
		"name": "兴安盟",
		"value": "VB0",
		"province": "内蒙古",
		"only": "c_215",
		"type": "city"
	}, {
		"id": "229",
		"ebaNo": "2001",
		"name": "宁波",
		"value": "M10",
		"province": "浙江",
		"only": "c_216",
		"type": "city"
		
	}, {
		"id": "230",
		"firstChar": "NING XIA ",
		"name": "宁夏",
		"value": "宁夏",
		"only": "p_021",
		"type": "province"
	}, {
		"id": "231",
		"ebaNo": "3401",
		"name": "银川",
		"value": "X10",
		"province": "宁夏",
		"only": "c_219",
		"type": "city"
	}, {
		"id": "232",
		"ebaNo": "1901",
		"name": "青岛",
		"value": "L10",
		"province": "山东",
		"only": "c_221",
		"type": "city"
	}, {
		"id": "233",
		"firstChar": "QING HAI ",
		"name": "青海",
		"value": "青海",
		"only": "p_023",
		"type": "province"
	}, {
		"id": "234",
		"ebaNo": "3501",
		"name": "西宁",
		"value": "Z10",
		"province": "青海",
		"only": "c_222",
		"type": "city"
	}, {
		"id": "235",
		"firstChar": "SHAN DONG ",
		"name": "山东",
		"value": "山东",
		"only": "p_024",
		"type": "province",
		"codeId":"C"
	}, {
		"id": "236",
		"ebaNo": "1019",
		"name": "滨州",
		"value": "CA0",
		"province": "山东",
		"only": "c_223",
		"type": "city"
	}, {
		"id": "237",
		"ebaNo": "1021",
		"name": "德州",
		"value": "CC0",
		"province": "山东",
		"only": "c_224",
		"type": "city"
	}, {
		"id": "238",
		"ebaNo": "1017",
		"name": "东营",
		"value": "C80",
		"province": "山东",
		"only": "c_225",
		"type": "city"
	}, {
		"id": "239",
		"ebaNo": "1025",
		"name": "菏泽",
		"value": "CF0",
		"province": "山东",
		"only": "c_226",
		"type": "city"
	}, {
		"id": "240",
		"ebaNo": "1001",
		"name": "济南",
		"value": "C10",
		"province": "山东",
		"only": "c_227",
		"type": "city"
	}, {
		"id": "241",
		"ebaNo": "1014",
		"name": "济宁",
		"value": "C50",
		"province": "山东",
		"only": "c_228",
		"type": "city"
	}, {
		"id": "242",
		"ebaNo": "1024",
		"name": "莱芜",
		"value": "CG0",
		"province": "山东",
		"only": "c_229",
		"type": "city"
	}, {
		"id": "243",
		"ebaNo": "1023",
		"name": "聊城",
		"value": "CE0",
		"province": "山东",
		"only": "c_230",
		"type": "city"
	}, {
		"id": "244",
		"ebaNo": "1015",
		"name": "临沂",
		"value": "C60",
		"province": "山东",
		"only": "c_231",
		"type": "city"
	}, {
		"id": "245",
		"ebaNo": "1020",
		"name": "日照",
		"value": "CB0",
		"province": "山东",
		"only": "c_232",
		"type": "city"
	}, {
		"id": "246",
		"ebaNo": "1018",
		"name": "泰安",
		"value": "C90",
		"province": "山东",
		"only": "c_233",
		"type": "city"
	}, {
		"id": "247",
		"ebaNo": "1016",
		"name": "威海",
		"value": "C70",
		"province": "山东",
		"only": "c_234",
		"type": "city"
	}, {
		"id": "248",
		"ebaNo": "1012",
		"name": "潍坊",
		"value": "C30",
		"province": "山东",
		"only": "c_235",
		"type": "city"
	}, {
		"id": "249",
		"ebaNo": "1011",
		"name": "烟台",
		"value": "C20",
		"province": "山东",
		"only": "c_236",
		"type": "city"
	}, {
		"id": "250",
		"ebaNo": "1022",
		"name": "枣庄",
		"value": "CD0",
		"province": "山东",
		"only": "c_237",
		"type": "city"
	}, {
		"id": "251",
		"ebaNo": "1013",
		"name": "淄博",
		"value": "C40",
		"province": "山东",
		"only": "c_238",
		"type": "city"
	}, {
		"id": "252",
		"firstChar": "SHAN XI ",
		"name": "山西",
		"value": "山西",
		"only": "p_025",
		"type": "province"
	}, {
		"id": "253",
		"ebaNo": "2415",
		"name": "长治",
		"value": "R70",
		"province": "山西",
		"only": "c_239",
		"type": "city"
	}, {
		"id": "254",
		"ebaNo": "2412",
		"name": "大同",
		"value": "R30",
		"province": "山西",
		"only": "c_240",
		"type": "city"
	}, {
		"id": "255",
		"ebaNo": "2416",
		"name": "晋城",
		"value": "R60",
		"province": "山西",
		"only": "c_241",
		"type": "city"
	}, {
		"id": "256",
		"ebaNo": "2413",
		"name": "晋中",
		"value": "R40",
		"province": "山西",
		"only": "c_242",
		"type": "city"
	}, {
		"id": "257",
		"ebaNo": "2411",
		"name": "临汾",
		"value": "R20",
		"province": "山西",
		"only": "c_243",
		"type": "city"
	}, {
		"id": "258",
		"ebaNo": "2417",
		"name": "吕梁",
		"value": "R80",
		"province": "山西",
		"only": "c_244",
		"type": "city"
	}, {
		"id": "259",
		"ebaNo": "2420",
		"name": "朔州",
		"value": "RA0",
		"province": "山西",
		"only": "c_245",
		"type": "city"
	}, {
		"id": "260",
		"ebaNo": "2401",
		"name": "太原",
		"value": "R10",
		"province": "山西",
		"only": "c_246",
		"type": "city"
	}, {
		"id": "261",
		"ebaNo": "2419",
		"name": "忻州",
		"value": "RB0",
		"province": "山西",
		"only": "c_247",
		"type": "city"
	}, {
		"id": "262",
		"ebaNo": "2418",
		"name": "阳泉",
		"value": "R90",
		"province": "山西",
		"only": "c_248",
		"type": "city"
	}, {
		"id": "263",
		"ebaNo": "2414",
		"name": "运城",
		"value": "R50",
		"province": "山西",
		"only": "c_249",
		"type": "city"
	}, {
		"id": "264",
		"firstChar": "SHAN XI ",
		"name": "陕西",
		"value": "陕西",
		"only": "p_026",
		"type": "province",
		"codeId":"7"
	}, {
		"id": "265",
		"ebaNo": "1213",
		"name": "安康",
		"value": "740",
		"province": "陕西",
		"only": "c_250",
		"type": "city"
	}, {
		"id": "266",
		"ebaNo": "1212",
		"name": "宝鸡",
		"value": "730",
		"province": "陕西",
		"only": "c_251",
		"type": "city"
	}, {
		"id": "267",
		"ebaNo": "1216",
		"name": "汉中",
		"value": "750",
		"province": "陕西",
		"only": "c_252",
		"type": "city"
	}, {
		"id": "268",
		"ebaNo": "1219",
		"name": "商洛",
		"value": "790",
		"province": "陕西",
		"only": "c_253",
		"type": "city"
	}, {
		"id": "269",
		"ebaNo": "1218",
		"name": "铜川",
		"value": "780",
		"province": "陕西",
		"only": "c_254",
		"type": "city"
	}, {
		"id": "270",
		"ebaNo": "1215",
		"name": "渭南",
		"value": "760",
		"province": "陕西",
		"only": "c_255",
		"type": "city"
	}, {
		"id": "271",
		"ebaNo": "1201",
		"name": "西安",
		"value": "710",
		"province": "陕西",
		"only": "c_256",
		"type": "city"
	}, {
		"id": "272",
		"ebaNo": "1211",
		"name": "咸阳",
		"value": "720",
		"province": "陕西",
		"only": "c_257",
		"type": "city"
	}, {
		"id": "273",
		"ebaNo": "1217",
		"name": "延安",
		"value": "7A0",
		"province": "陕西",
		"only": "c_258",
		"type": "city"
	}, {
		"id": "274",
		"ebaNo": "1214",
		"name": "榆林",
		"value": "770",
		"province": "陕西",
		"only": "c_259",
		"type": "city"
	}, {
		"id": "275",
		"firstChar": "SHANG HAI ",
		"name": "上海",
		"value": "上海",
		"only": "p_027",
		"type": "province",
		"codeId":"4"
	}, {
		"id": "276",
		"ebaNo": "0401",
		"name": "上海",
		"value": "410",
		"province": "上海",
		"only": "c_260",
		"type": "city"
	}, {
		"id": "277",
		"ebaNo": "1601",
		"name": "深圳",
		"value": "I10",
		"province": "广东",
		"only": "c_261",
		"type": "city"
		
	}, {
		"id": "278",
		"firstChar": "SI CHUAN ",
		"name": "四川",
		"value": "四川",
		"only": "p_029",
		"type": "province",
		"codeId":"4"
	}, {
		"id": "279",
		"ebaNo": "0530",
		"name": "阿坝",
		"value": "5M0",
		"province": "四川",
		"only": "c_262",
		"type": "city"
	}, {
		"id": "280",
		"ebaNo": "0525",
		"name": "巴中",
		"value": "5H0",
		"province": "四川",
		"only": "c_263",
		"type": "city"
	}, {
		"id": "281",
		"ebaNo": "0501",
		"name": "成都",
		"value": "510",
		"province": "四川",
		"only": "c_264",
		"type": "city"
	}, {
		"id": "282",
		"ebaNo": "0501",
		"name": "成都郊县",
		"value": "5L0",
		"province": "四川",
		"only": "c_265",
		"type": "city"
	}, {
		"id": "283",
		"ebaNo": "0515",
		"name": "达州",
		"value": "5D0",
		"province": "四川",
		"only": "c_266",
		"type": "city"
	}, {
		"id": "284",
		"ebaNo": "0514",
		"name": "德阳",
		"value": "530",
		"province": "四川",
		"only": "c_267",
		"type": "city"
	}, {
		"id": "285",
		"ebaNo": "0529",
		"name": "甘孜",
		"value": "5N0",
		"province": "四川",
		"only": "c_268",
		"type": "city"
	}, {
		"id": "286",
		"ebaNo": "0523",
		"name": "广安",
		"value": "5E0",
		"province": "四川",
		"only": "c_269",
		"type": "city"
	}, {
		"id": "287",
		"ebaNo": "0526",
		"name": "广元",
		"value": "5G0",
		"province": "四川",
		"only": "c_270",
		"type": "city"
	}, {
		"id": "288",
		"ebaNo": "0516",
		"name": "乐山",
		"value": "5A0",
		"province": "四川",
		"only": "c_271",
		"type": "city"
	}, {
		"id": "289",
		"ebaNo": "0527",
		"name": "凉山",
		"value": "5I0",
		"province": "四川",
		"only": "c_272",
		"type": "city"
	}, {
		"id": "290",
		"ebaNo": "0522",
		"name": "眉山",
		"value": "570",
		"province": "四川",
		"only": "c_273",
		"type": "city"
	}, {
		"id": "291",
		"ebaNo": "0511",
		"name": "绵阳",
		"value": "520",
		"province": "四川",
		"only": "c_274",
		"type": "city"
	}, {
		"id": "292",
		"ebaNo": "0512",
		"name": "南充",
		"value": "540",
		"province": "四川",
		"only": "c_275",
		"type": "city"
	}, {
		"id": "293",
		"ebaNo": "0518",
		"name": "内江",
		"value": "5B0",
		"province": "四川",
		"only": "c_276",
		"type": "city"
	}, {
		"id": "294",
		"ebaNo": "0528",
		"name": "攀枝花",
		"value": "5J0",
		"province": "四川",
		"only": "c_277",
		"type": "city"
	}, {
		"id": "295",
		"ebaNo": "0520",
		"name": "遂宁",
		"value": "560",
		"province": "四川",
		"only": "c_278",
		"type": "city"
	}, {
		"id": "296",
		"ebaNo": "0524",
		"name": "雅安",
		"value": "5F0",
		"province": "四川",
		"only": "c_279",
		"type": "city"
	}, {
		"id": "297",
		"ebaNo": "0513",
		"name": "宜宾",
		"value": "550",
		"province": "四川",
		"only": "c_280",
		"type": "city"
	}, {
		"id": "298",
		"ebaNo": "0521",
		"name": "资阳",
		"value": "580",
		"province": "四川",
		"only": "c_281",
		"type": "city"
	}, {
		"id": "299",
		"ebaNo": "0519",
		"name": "自贡",
		"value": "590",
		"province": "四川",
		"only": "c_282",
		"type": "city"
	}, {
		"id": "300",
		"ebaNo": "0517",
		"name": "泸州",
		"value": "5C0",
		"province": "四川",
		"only": "c_283",
		"type": "city"
	}, {
		"id": "301",
		"firstChar": "TIAN JIN ",
		"name": "天津",
		"value": "天津",
		"only": "p_030",
		"type": "province",
		"codeId":"E"
	}, {
		"id": "302",
		"ebaNo": "1101",
		"name": "天津",
		"value": "E10",
		"province": "天津",
		"only": "c_284",
		"type": "city"
	}, {
		"id": "303",
		"firstChar": "XIN JIANG ",
		"name": "新疆",
		"value": "新疆",
		"only": "p_031",
		"type": "province"
	}, {
		"id": "304",
		"ebaNo": "2821",
		"name": "阿克苏",
		"value": "S90",
		"province": "新疆",
		"only": "c_285",
		"type": "city"
	}, {
		"id": "305",
		"ebaNo": "2815",
		"name": "巴音郭楞",
		"value": "S70",
		"province": "新疆",
		"only": "c_286",
		"type": "city"
	}, {
		"id": "306",
		"ebaNo": "2819",
		"name": "博州",
		"value": "SB0",
		"province": "新疆",
		"only": "c_287",
		"type": "city"
	}, {
		"id": "307",
		"ebaNo": "2816",
		"name": "昌吉",
		"value": "S60",
		"province": "新疆",
		"only": "c_288",
		"type": "city"
	}, {
		"id": "308",
		"ebaNo": "2811",
		"name": "哈密",
		"value": "S40",
		"province": "新疆",
		"only": "c_289",
		"type": "city"
	}, {
		"id": "309",
		"ebaNo": "2817",
		"name": "喀什",
		"value": "S80",
		"province": "新疆",
		"only": "c_290",
		"type": "city"
	}, {
		"id": "310",
		"ebaNo": "2820",
		"name": "克拉玛依",
		"value": "SC0",
		"province": "新疆",
		"only": "c_291",
		"type": "city"
	}, {
		"id": "311",
		"ebaNo": "0",
		"name": "奎屯",
		"value": "SD0",
		"province": "新疆",
		"only": "c_292",
		"type": "city"
	}, {
		"id": "312",
		"ebaNo": "2813",
		"name": "石河子",
		"value": "S20",
		"province": "新疆",
		"only": "c_293",
		"type": "city"
	}, {
		"id": "313",
		"ebaNo": "2812",
		"name": "塔城",
		"value": "S50",
		"province": "新疆",
		"only": "c_294",
		"type": "city"
	}, {
		"id": "314",
		"ebaNo": "2818",
		"name": "吐鲁番",
		"value": "SA0",
		"province": "新疆",
		"only": "c_295",
		"type": "city"
	}, {
		"id": "315",
		"ebaNo": "2801",
		"name": "乌鲁木齐",
		"value": "S10",
		"province": "新疆",
		"only": "c_296",
		"type": "city"
	}, {
		"id": "316",
		"ebaNo": "2814",
		"name": "伊犁",
		"value": "S30",
		"province": "新疆",
		"only": "c_297",
		"type": "city"
	}, {
		"id": "317",
		"firstChar": "YUN NAN ",
		"name": "云南",
		"value": "云南",
		"only": "p_032",
		"type": "province"
	}, {
		"id": "318",
		"ebaNo": "2321",
		"name": "保山",
		"value": "PC0",
		"province": "云南",
		"only": "c_298",
		"type": "city"
	}, {
		"id": "319",
		"ebaNo": "2316",
		"name": "楚雄",
		"value": "P70",
		"province": "云南",
		"only": "c_299",
		"type": "city"
	}, {
		"id": "320",
		"ebaNo": "2311",
		"name": "大理",
		"value": "P40",
		"province": "云南",
		"only": "c_300",
		"type": "city"
	}, {
		"id": "321",
		"ebaNo": "2319",
		"name": "德宏",
		"value": "PA0",
		"province": "云南",
		"only": "c_301",
		"type": "city"
	}, {
		"id": "322",
		"ebaNo": "0",
		"name": "迪庆",
		"value": "PF0",
		"province": "云南",
		"only": "c_302",
		"type": "city"
	}, {
		"id": "323",
		"ebaNo": "2313",
		"name": "红河",
		"value": "P30",
		"province": "云南",
		"only": "c_303",
		"type": "city"
	}, {
		"id": "324",
		"ebaNo": "2301",
		"name": "昆明",
		"value": "P10",
		"province": "云南",
		"only": "c_304",
		"type": "city"
	}, {
		"id": "325",
		"ebaNo": "2317",
		"name": "丽江",
		"value": "P80",
		"province": "云南",
		"only": "c_305",
		"type": "city"
	}, {
		"id": "326",
		"ebaNo": "2318",
		"name": "临沧",
		"value": "PE0",
		"province": "云南",
		"only": "c_306",
		"type": "city"
	}, {
		"id": "327",
		"ebaNo": "0",
		"name": "怒江",
		"value": "PG0",
		"province": "云南",
		"only": "c_307",
		"type": "city"
	}, {
		"id": "328",
		"ebaNo": "2320",
		"name": "普洱",
		"value": "P90",
		"province": "云南",
		"only": "c_308",
		"type": "city"
	}, {
		"id": "329",
		"ebaNo": "2315",
		"name": "曲靖",
		"value": "P60",
		"province": "云南",
		"only": "c_309",
		"type": "city"
	}, {
		"id": "330",
		"ebaNo": "2322",
		"name": "文山",
		"value": "PB0",
		"province": "云南",
		"only": "c_310",
		"type": "city"
	}, {
		"id": "331",
		"ebaNo": "2314",
		"name": "西双版纳",
		"value": "P50",
		"province": "云南",
		"only": "c_311",
		"type": "city"
	}, {
		"id": "332",
		"ebaNo": "2312",
		"name": "玉溪",
		"value": "P20",
		"province": "云南",
		"only": "c_312",
		"type": "city"
	}, {
		"id": "333",
		"ebaNo": "2323",
		"name": "昭通",
		"value": "PD0",
		"province": "云南",
		"only": "c_313",
		"type": "city"
	}, {
		"id": "334",
		"firstChar": "ZHE JIANG ",
		"name": "浙江",
		"value": "浙江",
		"only": "p_033",
		"type": "province",
		"codeId":"B"
	}, {
		"id": "335",
		"ebaNo": "0901",
		"name": "杭州",
		"value": "B10",
		"province": "浙江",
		"only": "c_314",
		"type": "city"
	}, {
		"id": "336",
		"ebaNo": "0913",
		"name": "湖州",
		"value": "B60",
		"province": "浙江",
		"only": "c_315",
		"type": "city"
	}, {
		"id": "337",
		"ebaNo": "0917",
		"name": "嘉兴",
		"value": "B70",
		"province": "浙江",
		"only": "c_316",
		"type": "city"
	}, {
		"id": "338",
		"ebaNo": "0914",
		"name": "金华",
		"value": "B40",
		"province": "浙江",
		"only": "c_317",
		"type": "city"
	}, {
		"id": "339",
		"ebaNo": "0915",
		"name": "丽水",
		"value": "B80",
		"province": "浙江",
		"only": "c_318",
		"type": "city"
	}, {
		"id": "340",
		"ebaNo": "0911",
		"name": "绍兴",
		"value": "B20",
		"province": "浙江",
		"only": "c_319",
		"type": "city"
	}, {
		"id": "341",
		"ebaNo": "0912",
		"name": "台州",
		"value": "B30",
		"province": "浙江",
		"only": "c_320",
		"type": "city"
	}, {
		"id": "342",
		"ebaNo": "0916",
		"name": "温州",
		"value": "B50",
		"province": "浙江",
		"only": "c_321",
		"type": "city"
	}, {
		"id": "343",
		"ebaNo": "0918",
		"name": "舟山",
		"value": "B90",
		"province": "浙江",
		"only": "c_322",
		"type": "city"
	}, {
		"id": "344",
		"ebaNo": "0919",
		"name": "衢州",
		"value": "BA0",
		"province": "浙江",
		"only": "c_323",
		"type": "city"
	}, {
		"id": "345",
		"firstChar": "CHONG QING ",
		"name": "重庆",
		"value": "重庆",
		"only": "p_034",
		"type": "province",
		"codeId":"F"
	}, {
		"id": "346",
		"ebaNo": "1313",
		"name": "涪陵",
		"value": "F30",
		"province": "重庆",
		"only": "c_324",
		"type": "city"
	}, {
		"id": "347",
		"ebaNo": "1314",
		"name": "江津",
		"value": "F40",
		"province": "重庆",
		"only": "c_325",
		"type": "city"
	}, {
		"id": "348",
		"ebaNo": "1312",
		"name": "黔江",
		"value": "F50",
		"province": "重庆",
		"only": "c_326",
		"type": "city"
	}, {
		"id": "349",
		"ebaNo": "1311",
		"name": "万州",
		"value": "F20",
		"province": "重庆",
		"only": "c_327",
		"type": "city"
	}, {
		"id": "350",
		"ebaNo": "1301",
		"name": "重庆",
		"value": "F10",
		"province": "重庆",
		"only": "c_328",
		"type": "city"
	}, {
		"id": "351",
		"ebaNo": "0",
		"name": "重庆本部",
		"value": "F60",
		"province": "重庆",
		"only": "c_329",
		"type": "city"
	}],
	"value": "value",
	"only": "only",
	"label": "name",
	"identifier": "id"
}